### ISSUE TITLE
Ability to specify definitionPaths via /passive

### ISSUE THREAD

**Issue by devlife** [signalfx/PerfCounterReporter#24]
It would be great if we could specify definitionPaths in the new installer (especially via `passive`) like you could with the powershell script:

```
$config = @{
    APIToken='yourtoken';
    SourceType='netbios';
    SampleInterval = '00:00:01'; 
    DefinitionPaths = 'CounterDefinitions\system.counters','CounterDefinitions\webservice.counters'; 
    CounterNames = '\Processor(*)\% Processor Time';
}
./Install.ps1 $config
```

**Comment by molner** [comment]
To be clear, you're looking to be able to pass into the installer (via command line parameters) a list of one or more counter file definitions for PCR to use, correct? The "DefinitionPaths" element name is a bit wonky, so I just want to verify that what you're really interested in here is actually which counter definition files to use and not also potentially changing where they ultimately might be located (currently pathing is always relative to where PCR is laid down).

**Comment by devlife** [comment]
Yes that's exactly right.

**Comment by molner** [comment]
Got it. I'll take a look at this and see how much effort it would be.

**Comment by devlife** [comment]
Awesome thanks bud!
